version: "3.4"

services:
  app:
    build:
      context: .
    container_name: "amzn-app"
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - "./:/app"
    environment:
      CACHE_HOST: "cache"
      CACHE_PORT: "11211"

  cache:
    image: memcached:alpine3.16
    container_name: "amzn-cache"
